### ISSUE TITLE
Informazioni file note presente su mode

### ISSUE THREAD

**Issue by MiottoNicola** [nicolaprezza/progetto_PEL_22_23#10]
[note json.txt](https://github.com/nicolaprezza/progetto_PEL_22_23/files/11499623/note.json.txt)

buongiorno,
stavo facendo dei test al mio programma seguendo il file dato all'interno del modale del corso.
ho notato però che all'interno del file ci sono funzioni non dichiarate all'interno di json.hpp come la funzione .begin() e la funzione .get_double() (penso sia .get_number()).

inoltre sto avendo problemi a far funzionare questa parte di codice:
 json j3 = *(++it) // il secondo json della lista (2)
*(++it); // il terzo json della lista ([1,2,3])

qualcuno saprebbe darmi un aiuto?

**Comment by nicolaprezza** [comment]
Non capisco a cosa ti stai riferendo. In [json.hpp](https://github.com/nicolaprezza/progetto_PEL_22_23/blob/master/json.hpp) quelle funzioni non sono presenti. Stai forse guardando un commit vecchio del repository?

**Comment by nicolaprezza** [comment]
Per il progetto fate solo riferimento a questa pagina gitHub. Quel file di note era stato scritto al volo a lezione e contiene qualche errore. L'ho rimosso da moodle.
