### ISSUE TITLE
dubbio su null e json vuoto

### ISSUE THREAD

**Issue by dadezz** [nicolaprezza/progetto_PEL_22_23#12]
Buona sera, non mi è chiaro quando un json possa essere vuoto (ovvero, senza la scritta esplicita "null").
Espongo alcune casistiche:

file completamente vuoto: valido -> ritorna un json di tipo null?
lista senza elementi []: valida -> ritorna un json di tipo lista ma senza celle?
dizionario senza elementi {}: valido -> ritorna un json di tipo dizionario ma senza celle?
lista di cui un elemento è vuoto [12,,13]: valida? ritornerebbe una lista del tipo  [ json{12} -> json {null} -> json {13} ]?
dizionario di cui un elemento è vuoto {"a":a, ,"c":c}: idem come sopra?
stringa vuota "": valida?
dizionario di cui un elemento ha come chiave una stringa vuota  {"":a}: valido?
dizionario di cui un elemento ha come valore il vuoto  {"a":}: valido?
dizionario di cui un elemento non ha nulla {:}: valido?

sto avendo problemi a fare il parsing di tutte queste casistiche.
grazie

**Comment by nicolaprezza** [comment]
Buongiorno,

La specifica è chiara a riguardo:

"Globalmente, un file json è una lista, un dizionario, un numero (double), un booleano, una stringa, oppure null."

"File vuoto" (o assenza di valore) non compare nella lista. Ovviamente le liste e i dizionari possono essere vuoti, così come una stringa può non contenere alcun carattere. Questi sono però oggetti JSON che ricadono nelle 6 categorie sopra e non sono quindi il file vuoto.
