### ISSUE TITLE
Definizione operatori

### ISSUE THREAD

**Issue by mbert02** [nicolaprezza/progetto_PEL_22_23#13]
https://github.com/nicolaprezza/progetto_PEL_22_23/blob/351ea781fdf1db3f11d870c6cd82c2cda83ebd4c/json.hpp#L70

La definizione degli operatori va dentro o fuori la struct impl e devono essere friend?

**Comment by jermp** [comment]
Ciao, come vedi, la loro definizione è fuori da `impl` e **non** è friend. Devi far fede a quello che è dichiarato in `json.hpp`.
