### ISSUE TITLE
Lettura file json

### ISSUE THREAD

**Issue by ghost** [nicolaprezza/progetto_PEL_22_23#14]
Buongiorno,
Ho un dubbio su come viene eseguita la lettura del file json.
Con la seguente funzione leggiamo il file in input:
`std::istream&` operator>>(std::istream& lhs, json& rhs);`

Non ho capito se il programma deve leggere un file di tipo json ad esempio usando la funzione open(fileName) di <fstream> o se il programma legge in input solamente dal cin, ad esempio:
json b;
cin>>b;      `//scrivo nello stream un file json tipo: [ "ciao", 33, null ] che viene salvato in b`
cout<<b;    `//il programma mi stampa ["ciao",33,null]`

**Comment by jermp** [comment]
Ciao,
il contenuto viene letto da uno _stream_, qualsiasi cosa esso sia: `std::cin` è lo standard input, ma potresti avere anche uno stream da file, o uno string stream. A lezione, abbiamo visto tutte queste possibilità.

Per esempio, ecco come potresti acquisire un oggetto json da file stream:

    std::string json_filename("test.json");
    json j;
    std::fstream input_stream(json_filename.c_str());
    // check if file has been opened correctly...
    input_stream >> j;

E per stampare, puoi fare:

    std::cout << j;
    
oppure aprire uno file stream di output e scrivere in contenuto su file.
