### ISSUE TITLE
Iteratori Const 

### ISSUE THREAD

**Issue by CarlottaZanotto26** [nicolaprezza/progetto_PEL_22_23#15]
Buongiorno, nel mio programma mi stanno dando problemi gli interatori begin e end const poichè mi danno come errore questo "a type qualifier is not allowed on a nonmember functionC/C+", ma non capisco quale sarebbe l'errore poichè cercando il motivo dell'errore viene inteso come non presente dentro la classe, come posso fare? O come posso risolvere? Inoltre mi da problemi al Begin in entrambi i casi, perchè dice che non riconosce che sono funzioni diverse (begin normale e begin const per esempio) 
Grazie mille

**Comment by nicolaprezza** [comment]
Ciao, purtroppo senza guardare il codice mi risulta impossibile capire. Se vuoi fissiamo un ricevimento, mandami una mail.
