### ISSUE TITLE
Header memory

### ISSUE THREAD

**Issue by MarcoMihaiCondrache** [nicolaprezza/progetto_PEL_22_23#16]
Salve, volevo chiedere se fosse possibile aggiungere `#include <memory>`  per permettere l'utilizzo di strumenti per la gestione più efficace della memoria, come per esempio l'utilizzo degli allocator, smart pointer e memory resources. Non dovrebbe cambiare nulla nei progetti esistenti ma permetterebbe a più persone di creare soluzioni più performanti, complesse e interessanti dal punto di vista didattico.

**Comment by nicolaprezza** [comment]
No, mi spiace. Vanno usati solo gli strumenti spiegati in classe e le performance non devono preoccuparvi troppo. In particolare, l'allocazione della memoria deve essere obbligatoriamente fatta con new/delete perchè è proprio una delle cose che dobbiamo verificare, essendo parte del programma. Chiaramente, sei libero di implementare una tua versione privata del codice con queste modifiche.
