### ISSUE TITLE
Lettura liste vuote

### ISSUE THREAD

**Issue by ZodiacalRelic** [nicolaprezza/progetto_PEL_22_23#17]
Volevo sapere se quando il parser legge una lista vuota '[ ]', devo andare a stampare [ null ] oppure solamente le parentesi con dentro niente [ ] ?
Perchè uno dei test case falliti dice che il file caricato non corrisponde a quello originale e l'unica differenza è che in quello stampato dal mio programma le liste sono vuote [ ] mentre in quello originale è presente null all'interno [null].

Testando il programma se leggo [null] poi vado a stampare [null].

**Comment by jermp** [comment]
Ciao,
la lista vuota, `[]`, è diversa da una lista il cui unico elemento è un oggetto JSON `null`.
Quindi se il parser acquisisce una lista vuota, stampi `[]`.
Se l'unico elemento della lista è un JSON `null`, allora stamperai `[null]`.
