### ISSUE TITLE
Problemi con le struct iterator

### ISSUE THREAD

**Issue by Riccardo-Preto** [nicolaprezza/progetto_PEL_22_23#18]
Buongiorno, vorrei chiedere aiuto riguardo ad un problema che mi dà il mio programma. Se provo a utilizzare gli iteratori o begin_list nel main in un file test.cpp, mi dice che json::list_iterator è un tipo incompleto e che non posso incrementarlo o fare altri operatori che ho definito in json.cpp. Se per esempio provo a mettere il main nel file json.cpp questi problemi sono risolti, ed il "problema di esempio" :
json j;
std::cin >> j;
json& y = *(++j.begin_list());
std::cout << y["quarta chiave"]["a"];
mi dà il risultato corretto. Ho provato a ridefinire in modo diverso le struct iterator e testato variazioni dei metodi ma il problema continua.

**Comment by nicolaprezza** [comment]
Domanda già fatta in precedenza: leggi le issue "closed".
