### ISSUE TITLE
gerarchie nel file.json

### ISSUE THREAD

**Issue by Das892126** [nicolaprezza/progetto_PEL_22_23#2]
Mi scusi professore le volevo chiedere una delucidazione sul file.json da parsare.
Mi chiedevo se fosse possibile avere come primo carattere un numero (double) e successivamente altri oggetti di tipo json (esempio 1) o se è necessario che il file.json cominci con una lista (esempio 2) oppure un dizionario (esempio 3) .

esempio 1:
4.3
null
true
[false, 5.6 , "sium" ]

esempio 2:
[false, 5.6 , "sium", {"key1": 4} ]
esempio 3:
{"key1": 4.0, "key2": [false, 5.6 , "sium" ]}

**Comment by nicolaprezza** [comment]
Leggi qui: 

https://github.com/nicolaprezza/progetto_PEL_22_23/blob/d842efd39ad7081b8bb7fbd9f8e6c11217a1f12e/README.md?plain=1#L17

Esempio 1 non è quindi valido (non è nessuna di queste cose: una lista, **un** dizionario, **un** numero (double), **un** booleano, **una** stringa, oppure **un** null). 

esempi 2 e 3 sono validi. 

Nota che un file json può contenere anche solo **un** numero/bool/null/stringa. Per esempio, questo è un valido file json:

3.14
