### ISSUE TITLE
Iterator end()

### ISSUE THREAD

**Issue by ghost** [nicolaprezza/progetto_PEL_22_23#20]
che cosa deve restituire la funzione end_list se ho una lista di questo tipo:
it  = [1,2,3,4] ovvero con questa struttura 1->2->3->4->nullptr
it.end_list();

end list dovrebbe restituire l'ultimo elemento (ovvero 4) o restituisce nullptr?

**Comment by jermp** [comment]
L'iteratore è un oggetto che serve a fornire un'interfaccia, quindi il suo comportamento prescinde dalla specifica implementazione. L'importante è che la coppia begin/end ti permetta di iterare su tutti gli elementi della lista.
Tipicamente uno dovrebbe scrivere un ciclo for come segue:

    for (auto it = j.begin(); it != j.end(); ++it) { ... }
    
e quindi `j.end()` dovrebbe ritornarti l'elemento *dopo* l'ultimo elemento (one-past the end, come abbiamo visto a lezione).
