### ISSUE TITLE
Test non eseguiti

### ISSUE THREAD

**Issue by LeonardoBoldrin** [nicolaprezza/progetto_PEL_22_23#22]
Buongiorno, 
controllando i risultati dei test case di oggi del progetto, ho notato che alcuni test non sono stati eseguiti o comunque non hanno prodotto risultati in results.txt, ci sono solo queste due righe: 

**** running test: copy_move ****

**** running test: load_save_file ****

solo questi, in tutti gli altri ho SUCCESS! tranne che in push_insert_iterators_operator[]. 
Nemmeno valgrind ha fornito un output in questi specifici casi. C'è un motivo per questo oppure c'è stato un problema?

**Comment by nicolaprezza** [comment]
Buongiorno, vuol dire che il programma è terminato in modo improvviso
(potrebbe essere una segfault). Dovresti progettare meglio i test case.

**Comment by LeonardoBoldrin** [comment]
Certo ma se fosse una segfault almeno mi darebbe l'errore segmentation fault immagino, qui ho solamente che i test non sono nemmeno iniziati

**Comment by nicolaprezza** [comment]
l'output valgrind in quei test case si interrompe dopo poche righe: il
programma crasha per qualche motivo. Sì, solitamente in caso di segfault
valgrind stampa qualche informazione in più, mentre qui non dice nulla.
L'unica soluzione è progettare meglio i test case (i nostri sono piuttosto
banali) e procedere con debugging.

Il giorno gio 17 ago 2023 alle ore 16:44 LeonardoBoldrin <
***@***.***> ha scritto:
