### ISSUE TITLE
incoerenza nel operator[] const

### ISSUE THREAD

**Issue by GiacomoGuidotto** [nicolaprezza/progetto_PEL_22_23#3]
Nella descrizione del operator[] viene descritto che in caso la entry nel dizionario non esista allora va creata e ritornata una reference a il nuovo oggetto, tuttavia questo operator ha anche il suo reciproco in un contesto const, che promette di non modificare l'oggetto. Tentare di creare una nuova entry in questo metodo viola il contesto const.
Questo si puo notare se si vuole usare il metodo predefinito insert per aggiungere un nuovo elemento che non è per contesti const
Suggerisco di optare per una json_exception in caso si cerchi di accedere a una entry che non esiste in un oggetto json const

**Comment by jermp** [comment]
Ciao, giusto.
Aggiorno la descrizione. Grazie per la segnalazione!
