### ISSUE TITLE
information to struct iterator

### ISSUE THREAD

**Issue by MiottoNicola** [nicolaprezza/progetto_PEL_22_23#4]
Buonasera,
controllando il file .hpp e la documentazione consegnata, 
sto riscontrando problemi nel capire a cosa serve e come utilizzare questa parte di codice:
```
struct list_iterator;
struct dictionary_iterator;
struct const_list_iterator;
struct const_dictionary_iterator;
```
Dal nome penso serva per poter compiere tutte le operazioni sulle liste, ma non capisco come poterla implementare e soprattutto utilizzare all'interno di altre funzioni.
Qualcuno saprebbe darmi dei consigli?

grazie mille.

**Comment by nicolaprezza** [comment]
sono iteratori: vanno implementati come visto a lezione (l'interfaccia è la stessa: leggi anche [qui](https://github.com/nicolaprezza/progetto_PEL_22_23/blob/9666de4381b71d8238f89c8d9525198612042e82/README.md?plain=1#L159)).

**Comment by MarcoMihaiCondrache** [comment]
Continuo questa issue per non aprirne un'altra, l'implementazione delle struct riguardanti agli iterator dovrebbe essere inserita all'interno del file header json.hpp (va in conflitto con le richieste del progetto). Creando l'implementazione all'interno di json.cpp il compilatore non sa quanta memoria allocare per la struct degli iterator provocando l'errore:

`Calling 'begin_list' with incomplete return type 'json::list_iterator'`

nel momento in cui si prova ad utilizzare gli iterator all'esterno della classe json. Per esempio nel main di un file di test.

La stessa cosa però non vale per la struct impl in quanto non è accessibile all'esterno.

Riferimento: https://learn.microsoft.com/en-us/cpp/c-language/incomplete-types?view=msvc-170

**Comment by nicolaprezza** [comment]
Basta includere #include "json.cpp" nel file "test.cpp" contenente il tuo main e compilare con "g++ test.cpp"

Altra possibile causa del problema: in "json.cpp", la definizione degli iteratori deve precedere la definizione delle funzioni che li utilizzano. 

Esempio: 

**a.h : **

struct a{
	struct b;
	b f();
};


**a.cpp : **

#include "a.h"

struct a::b{
	int x;
};

a::b a::f(){
	return {5};
}


**main.cpp : **

#include <iostream>
#include "a.cpp"

int main(){
	a y;
	std::cout << y.f().x << std::endl;
}


**compila con**: g++ main.cpp
