### ISSUE TITLE
Push back

### ISSUE THREAD

**Issue by tiume01** [nicolaprezza/progetto_PEL_22_23#5]
Salve prof,
Non ho capito bene la funzione push back. Se per esempio viene creato un json j, poi un altro json j2, quando viene fatto il push back su j devo mettere il contenuto di j2 alla fine del contenuto di j oppure fare "j -> next = j2" ?

**Comment by nicolaprezza** [comment]
La [push_back](https://github.com/nicolaprezza/progetto_PEL_22_23/blob/08f848af12e74e04026bb3155076108b9ab9e381/README.md?plain=1#L323) aggiunge un json in fondo ad una lista di json.

Per poter chiamare push_back, il json j deve essere di tipo lista:

json j; //nuovo json (costruttore di default)
j.set_list(); // rendo il json di tipo lista (vuota)
json j2;
j.push_back(j2); // aggiungo j2 in fondo alla lista di j.

"j -> next = j2" non è codice ben formato perchè (1) j non è un puntatore e (2) json non contiene il membro "next". La lista deve essere implementata dentro json::impl.

**Comment by jermp** [comment]
Se fai

    parent.push_back(j);
    parent.push_back(j2);

dove `parent` è un json di "tipo" lista, allora appendi in ordine alla lista prima il json `j` e poi `j2`.
Un oggetto json non deve avere un attributo `next`.
