### ISSUE TITLE
operator[]

### ISSUE THREAD

**Issue by tiume01** [nicolaprezza/progetto_PEL_22_23#7]
ho un dubbio sulla consegna in questa parte : il metodo operator[] deve inserire nel dizionario una nuova coppia chiave-valore la cui chiave è key e il cui valore è un json costruito con il costruttore di default (i.e., un json il cui contenuto è null), ed infine restituire una reference a questo nuovo json appena costruito;
Devo utilizzare la insert per inserire questo nuovo elemento ? E quindi è da aggiungere alla fine? Io avevo pensato di scorrere tutto il dizionario e se trovo la chiave ritorno il valore corrispondente, altrimenti chiamo la insert (?)

**Comment by jermp** [comment]
Solo se la chiave non viene trovata devi effettuare un inserimento, come è descritto nella specifica.
