### ISSUE TITLE
file in input

### ISSUE THREAD

**Issue by MiottoNicola** [nicolaprezza/progetto_PEL_22_23#8]
Buongiorno,
controllando la documentazione e gli esempi forniti trovo tantissime differenze di input al programma.
All'interno del link https://github.com/jdorfman/awesome-json-datasets tutti i file json iniziano e terminano con una parentesi graffa.
Da quello che leggo invece nel readme del progetto gli input sono di diverse fonti, possono essere dizionari, liste, bool, string, null, duole e tutti possono essere l'inizio del file json.

vorrei capire cortesemente con quale formato viene dato in input il file json al programma per capire come creare il parser. 
grazie mille.

**Comment by jermp** [comment]
Ciao,
Dato che un json può essere una delle 6 cose che hai menzionato, l’input non è necessariamente un dizionario, bensì una struttura gerarchica che può contenere un misto di quelle 6 cose. Quindi il file può “cominciare” con una lista anziché un dizionario.

È compito della grammatica implementata nel parser gestire tali casi.

**Comment by MiottoNicola** [comment]
ultima domanda, i dati di tipo double possono essere anche negativi? @jermp

**Comment by dadezz** [comment]
Aggiungo se possibile una domanda, a proposito dei tipi di Json. null che cos'è? c'è proprio scritto null o è il file/lista/dizionario vuoto?

**Comment by jermp** [comment]
`null` è un valore che significa "valore nullo". Lista vuota è `[]` e dizionario vuoto è `{}`, quindi entrambi sono due cose diverse da `null`.
