### ISSUE TITLE
Trailing Comma

### ISSUE THREAD

**Issue by Friedchicken-42** [nicolaprezza/progetto_PEL_22_23#9]
https://github.com/nicolaprezza/progetto_PEL_22_23/blob/0201fdc58824942b0fd6a78392c55ef73a258c62/README.md?plain=1#L53

Normalmente JSON non supporta le trailing comma, in questo caso dobbiamo accettarle o lanciare un'eccezione?

**Comment by nicolaprezza** [comment]
Era un errore di README, grazie per la segnalazione.
